const { emailQueue } = require("../queues/emailQueue");
const Log = require("../models/Log");
const Campaign = require("../models/Campaign");
const CampaignLog = require("../models/CampaignLog");
const crypto = require("crypto");

const CampaignTemplate = require("../models/CampaignTemplate");
const IP = require("../models/IP");
const Offer = require("../models/Offer");
const MonitoringMailbox = require("../models/MonitoringMailbox");
const { generateMessageId } = require("../utils/patternGenerator");
const TagEngine = require("../utils/tagEngine");
const ReputationScore = require("../models/ReputationScore");
const SmtpDetail = require("../models/SmtpDetail");
const { parseIpPool } = require("../utils/parseIpPool");
const { spaceEmailQueue } = require("../queues/spaceEmailQueue");
const socketService = require("../services/socketService");

const applySearchReplace = (text, searchReplaceStr) => {
  if (!text || !searchReplaceStr) return text;
  let result = text;
  const pairs = searchReplaceStr.split("\n");
  for (const pair of pairs) {
    const [search, replace] = pair.split("|");
    if (search && replace) {
      try {
        const escapedSearch = search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        const regex = new RegExp(escapedSearch, "g");
        result = result.replace(regex, replace);
      } catch (e) {
        console.error("Search/Replace Regex Error:", e);
      }
    }
  }
  return result;
};

/**
 * Build a replaceTags function for a single email address
 */
const buildReplaceTags = (email, opts) => {
  const { from_email, from_name, offer_id, domain, search_replace } = opts;

  const dateNow = new Date();
  const dateStr = dateNow.toLocaleDateString("en-GB").replace(/\//g, "-");
  const datetimeStr = dateNow.toUTCString();
  const emailDomain = email.split("@")[1] || "";
  const nameTag = emailDomain.replace(/[._-]/g, "").replace(/[0-9]/g, "");

  return (text) => {
    if (!text) return "";
    let processed = text
      .replace(/{email}/g, email)
      .replace(/{name}/g, nameTag)
      .replace(/{fromid}/g, from_email)
      .replace(/{fromname}/g, from_name)
      .replace(/{datetime}/g, datetimeStr)
      .replace(/{date}/g, dateStr)
      .replace(/{msgid}/g, "") // Message-ID is natively generated by nodemailer now
      .replace(/{domain}/g, domain || "")
      .replace(
        /{unsl}/g,
        `http://${domain || "localhost"}/un.php?${offer_id || "0"}|${email}`,
      )
      .replace(
        /{ourl}/g,
        `http://${domain || "localhost"}/un.php?${offer_id || "0"}|${email}`,
      )
      .replace(
        /{oln}/g,
        `http://${domain || "localhost"}/un.php?${offer_id || "0"}|${email}`,
      )
      .replace(
        /{base_trk}/g,
        Buffer.from(`${offer_id || "0"}|${email}`).toString("base64"),
      )
      .replace(
        /{hex_trk}/g,
        Buffer.from(`${offer_id || "0"}|${email}`).toString("hex"),
      )
      .replace(
        /\(\(_track_\)\)/g,
        crypto.createHash("md5").update(email).digest("hex"),
      );

    processed = TagEngine.process(processed, { email, domain, offer_id });
    processed = applySearchReplace(processed, search_replace);
    return processed;
  };
};

/**
 * Queue a single email job
 */
const queueEmail = async (email, currentIp, campaignId, opts) => {
  const {
    from_email,
    from_name,
    headers,
    subject,
    message_html,
    message_plain,
    mode,
    subject_enc,
    from_enc,
    msg_type,
    charset,
    encoding,
    charset_alt,
    encoding_alt,
    reply_to,
    xmailer,
    domain,
    offer_id,
    search_replace,
    wait_time,
    dashboardLogId,
    message_id,
  } = opts;

  const replaceTags = buildReplaceTags(email.trim(), {
    from_email,
    from_name,
    offer_id,
    domain,
    search_replace,
  });

  await emailQueue.add("send-email", {
    campaign_id: campaignId,
    from_email,
    from_name: replaceTags(from_name),
    mailing_ip: currentIp,
    headers: replaceTags(headers),
    subject: replaceTags(subject),
    body_html: replaceTags(message_html),
    body_plain: replaceTags(message_plain),
    email: email.trim(),
    mode,
    subject_enc,
    from_enc,
    msg_type,
    charset,
    encoding,
    charset_alt,
    encoding_alt,
    msgId: message_id,
    reply_to,
    xmailer,
    offer_id,
    wait_time: Number(wait_time) || 0,
    dashboardLogId,
  });
};

const sendEmail = async (req, res) => {
  const {
    from_email,
    from_name,
    mailing_ip,
    headers,
    subject,
    message_html,
    message_plain,
    emails,
    mode = "test",
    subject_enc,
    from_enc,
    msg_type,
    charset,
    encoding,
    charset_alt,
    encoding_alt,
    sen_t = "manual",
    offer_id,
    template_name,
    domain,
    message_id,
    reply_to,
    xmailer,
    total_send,
    data_file,
    search_replace,
    inbox_percent,
    mail_after,
    sleep_time,
    limit_to_send,
    wait_time,
    accs,
    interval_time,
  } = req.body;

  // ── Validate required fields ──────────────────────────────────────────────
  if (!from_email || !mailing_ip) {
    return res.status(400).json({
      message: "Missing required fields: from_email, mailing_ip",
    });
  }
  // emails OR data_file must be provided
  if (!emails && !data_file) {
    return res.status(400).json({
      message:
        "Either paste emails in the Emails field or provide a Data File name.",
    });
  }

  try {
    // ── Parse IP Pool (supports Format 1: IP|email and Format 2: 3-line group) ─
    const ipPool = parseIpPool(mailing_ip);
    if (ipPool.length === 0) {
      return res.status(400).json({
        message:
          "No valid IPs found. Use 'IP|email' per line, or 3-line groups (IP / email / name).",
      });
    }
    const primaryEntry = ipPool[0];
    const primaryIp = primaryEntry.ip;

    // ── Reputation Guard (only for bulk modes) ────────────────────────────
    if (mode === "bulk") {
      if (primaryIp) {
        const rep = await ReputationScore.findOne({ assetValue: primaryIp });
        if (rep && rep.status === "paused") {
          return res.status(403).json({
            message: `Send Blocked: IP ${primaryIp} is paused (Inbox Score: ${rep.inboxScore?.toFixed(1)}%). Check Intelligence Dashboard.`,
          });
        }
      }
      if (domain) {
        const domRep = await ReputationScore.findOne({ assetValue: domain });
        if (domRep && domRep.status === "paused") {
          return res.status(403).json({
            message: `Send Blocked: Domain ${domain} is paused due to low inbox placement. Check Intelligence Dashboard.`,
          });
        }
      }
    }

    // ── Determine mode type ───────────────────────────────────────────────
    const campaignType = `${mode}_${sen_t}`;

    // ── Build email list: data_file (server) takes priority over textarea ─
    let rawEmailList = "";

    if (data_file && data_file.trim()) {
      const { DATA_PATH, BUFFER_PATH } = require("../config/paths");
      const fs = require("fs");
      const nodePath = require("path");

      const df = data_file.trim();
      // Try multiple locations:
      // 1. Direct path as provided
      // 2. DATA_PATH + filename
      // 3. BUFFER_PATH + filename (basename)

      const primaryPath = nodePath.isAbsolute(df)
        ? df
        : nodePath.join(DATA_PATH, df);
      const bufferFallbackPath = nodePath.join(
        BUFFER_PATH,
        nodePath.basename(df),
      );

      let finalPath = null;
      if (fs.existsSync(primaryPath)) {
        finalPath = primaryPath;
      } else if (fs.existsSync(bufferFallbackPath)) {
        finalPath = bufferFallbackPath;
      }

      if (finalPath) {
        try {
          rawEmailList = fs.readFileSync(finalPath, "utf-8");
        } catch (fileErr) {
          console.error(
            `[emailController] Error reading file "${finalPath}":`,
            fileErr.message,
          );
          rawEmailList = emails || "";
        }
      } else {
        console.warn(
          `[emailController] data_file "${df}" not found in ${DATA_PATH} or ${BUFFER_PATH}. Fallback to textarea.`,
        );
        rawEmailList = emails || "";
      }
    } else {
      rawEmailList = emails || "";
    }

    let targetEmails = rawEmailList
      .split("\n")
      .map((e) => e.trim())
      .filter(Boolean);

    if (targetEmails.length === 0) {
      return res.status(400).json({
        message:
          "No valid email addresses found. Check your email list or data file.",
      });
    }

    // ── Apply total_send hard cap ─────────────────────────────────────────
    const totalSendCap = Number(total_send);
    if (totalSendCap > 0 && targetEmails.length > totalSendCap) {
      targetEmails = targetEmails.slice(0, totalSendCap);
    }

    const emailOpts = {
      from_email,
      from_name,
      headers,
      subject,
      message_html,
      message_plain,
      mode,
      subject_enc,
      from_enc,
      msg_type,
      charset,
      encoding,
      charset_alt,
      encoding_alt,
      reply_to,
      xmailer,
      domain,
      offer_id,
      search_replace,
      wait_time: Number(wait_time) || 0,
      message_id: message_id || "",
    };

    const { campaign_id: existingCampaignId } = req.body;
    let campaign = null;
    let startIndex = 0;

    if (existingCampaignId) {
      campaign = await Campaign.findById(existingCampaignId);
    }

    // Only reset stats if the campaign reached "Completed" or if it's a brand new campaign.
    // If it's "Stopped" or "Running", we consider this a continuation of the same job.
    const shouldReset = !campaign || campaign.status === "Completed";

    const updateData = {
      template_name: template_name || "Manual Sending",
      offer_id: offer_id || "Manual",
      server: primaryIp || "Unknown",
      data_file: data_file || "emails_field",
      total_emails: targetEmails.length,
      status: "Running", // Always set to running when a send is initiated
      mode,
      sen_t,
      type: campaignType,
      domain: domain || "",
      from_email: from_email || "",
      mail_after: Number(mail_after) || 100,
      sleep_time: Number(sleep_time) || 5,
      limit_to_send: Number(limit_to_send) || 500,
      ip_list: ipPool.map((e) => e.ip),
      total_queued: 0, // This will be updated later based on actual queued emails
      // Configuration snapshot
      accs: accs || mailing_ip || "",
      headers: headers || "",
      subject: subject || "",
      from_name: from_name || "",
      emails: emails || "",
      msg_type: msg_type || "html",
      message_html: message_html || "",
      message_plain: message_plain || "",
      search_replace: search_replace || "",
      total_send: String(total_send || ""),
      wait_time: String(wait_time || "2"),
      message_id: message_id || "",
      inbox_percent: Number(inbox_percent) || 50,
      reply_to: reply_to || "0",
      xmailer: xmailer || "0",
      interval_time: String(interval_time || ""),
      charset: charset || "UTF-8",
      encoding: encoding || "8bit",
      charset_alt: charset_alt || "UTF-8",
      encoding_alt: encoding_alt || "8bit",
    };

    if (shouldReset) {
      Object.assign(updateData, {
        success_count: 0,
        error_count: 0,
        bounce_count: 0,
        inbox_count: 0,
        spam_count: 0,
        promo_count: 0,
        guardian_logs: [],
        start_time: new Date(),
      });
    } else {
      // If resuming, calculate startIndex for targetEmails and pIdx for IP round-robin
      startIndex = (campaign.success_count || 0) + (campaign.error_count || 0);
      // Ensure startIndex doesn't exceed total_emails
      startIndex = Math.min(startIndex, targetEmails.length);
      // Update total_emails if the list changed
      updateData.total_emails = targetEmails.length;
    }

    if (campaign) {
      campaign = await Campaign.findByIdAndUpdate(campaign._id, updateData, {
        new: true,
      });
    } else {
      campaign = await Campaign.create(updateData);
    }

    const campaignId = campaign._id;

    const startLog = await CampaignLog.create({
      campaign_id: campaignId,
      log_text: `[${campaignType.toUpperCase()}] Campaign started | Emails: ${targetEmails.length} | Mode: ${mode} | Sending: ${sen_t}`,
      type: "info",
    });
    socketService.emitLog(campaignId, startLog, campaign);

    // ── Dashboard Log (Initialize with 0, update in worker) ───────────────
    const dashLog = await Log.create({
      mailer: "Admin",
      template_id: template_name || "Manual",
      interface: mode === "bulk" ? "BULK SEND" : "TEST SEND",
      server: primaryIp || "Unknown",
      offer_id: offer_id || "Manual",
      domain:
        domain ||
        (from_email && from_email.includes("@")
          ? from_email.split("@")[1]
          : "Unknown"),
      from: from_email || "unknown@domain.com",
      test_sent: 0,
      bulk_test_sent: 0,
      bulk_test: 0,
      error: 0,
    });

    const dashboardLogId = dashLog ? dashLog._id : null;

    // ════════════════════════════════════════════════════════════════════════
    //  MODE BRANCHES
    // ════════════════════════════════════════════════════════════════════════

    if (
      campaignType === "test_manual" ||
      (campaignType === "test_auto" &&
        (await MonitoringMailbox.countDocuments({ isActive: true })) === 0)
    ) {
      if (!ipPool || ipPool.length === 0) {
        return res.status(400).json({
          message:
            "No active IPs or SMTP accounts found. Please check your setup.",
        });
      }
      // ── TEST + MANUAL (or fallback AUTO): Round-robin across ip pool ──
      let pIdx = startIndex % ipPool.length;
      const batchEmails = targetEmails.slice(startIndex);

      for (const email of batchEmails) {
        const entry = ipPool[pIdx % ipPool.length];
        pIdx++;
        await queueEmail(email, entry.ip, campaignId, {
          ...emailOpts,
          from_name: entry.from_name || from_name,
          from_email: entry.from_email || from_email,
          dashboardLogId,
        });
      }

      const queueLog = await CampaignLog.create({
        campaign_id: campaignId,
        log_text: `[${campaignType.toUpperCase()}] Queued ${batchEmails.length} emails (starting from ${startIndex}).`,
        type: "info",
      });
      socketService.emitLog(campaignId, queueLog, campaign);

      return res.json({
        message: "Test emails queued. Please check inboxes manually.",
        campaign_id: campaignId,
        count: batchEmails.length,
        mode: campaignType,
      });
    }

    if (campaignType === "test_auto") {
      const monitoringMailboxes = await MonitoringMailbox.find({
        isActive: true,
      });
      // Test + Auto: send from EACH IP to EACH monitoring mailbox (ignore start index for scoring)
      for (const entry of ipPool) {
        for (const mbox of monitoringMailboxes) {
          await queueEmail(mbox.email, entry.ip, campaignId, {
            ...emailOpts,
            from_name: entry.from_name || from_name,
            from_email: entry.from_email || from_email,
            dashboardLogId,
          });
        }
      }
      await Campaign.findByIdAndUpdate(campaignId, {
        total_queued: monitoringMailboxes.length * ipPool.length,
        total_emails: monitoringMailboxes.length * ipPool.length,
      });
      const autoLog = await CampaignLog.create({
        campaign_id: campaignId,
        log_text: `[TEST+AUTO] Sent to ${monitoringMailboxes.length} monitoring mailboxes from ${ipPool.length} IP(s).`,
        type: "info",
      });
      socketService.emitLog(campaignId, autoLog, campaign);

      return res.json({
        message: `Test emails sent to monitoring mailboxes. Auto IMAP scan scheduled.`,
        campaign_id: campaignId,
        count: monitoringMailboxes.length * ipPool.length,
        mode: campaignType,
      });
    }

    if (campaignType === "bulk_manual") {
      if (!ipPool || ipPool.length === 0) {
        return res.status(400).json({
          message:
            "No active IPs or SMTP accounts found. Please check your setup.",
        });
      }
      // ── BULK + MANUAL: Round-robin batch starting from offset ───────────
      const batchSize = Number(limit_to_send) || 500;
      const batchEmails = targetEmails.slice(
        startIndex,
        startIndex + batchSize,
      );
      let pIdx = startIndex % ipPool.length;
      let queued = 0;

      for (const email of batchEmails) {
        const entry = ipPool[pIdx % ipPool.length];
        pIdx++;
        await queueEmail(email, entry.ip, campaignId, {
          ...emailOpts,
          from_name: entry.from_name || from_name,
          from_email: entry.from_email || from_email,
          dashboardLogId,
        });
        queued++;
      }

      await Campaign.findByIdAndUpdate(campaignId, { total_queued: queued });
      const bulkManualLog = await CampaignLog.create({
        campaign_id: campaignId,
        log_text: `[BULK+MANUAL] Queued batch of ${queued} emails (Offset: ${startIndex}, Remaining: ${targetEmails.length - (startIndex + queued)}).`,
        type: "info",
      });
      socketService.emitLog(campaignId, bulkManualLog, campaign);

      return res.json({
        message: `Batch queued: ${queued} emails dispatched.`,
        campaign_id: campaignId,
        count: queued,
        total_sent_so_far: startIndex + queued,
        total: targetEmails.length,
        mode: campaignType,
      });
    }

    if (campaignType === "bulk_auto") {
      if (!ipPool || ipPool.length === 0) {
        return res.status(400).json({
          message:
            "No active IPs or SMTP accounts found. Please check your setup.",
        });
      }
      // ── BULK + AUTO: First batch + start AutoRunner from offset ────────
      const batchSize = Number(mail_after) || 100;
      const firstBatch = targetEmails.slice(startIndex, startIndex + batchSize);
      let pIdx = startIndex % ipPool.length;

      for (const email of firstBatch) {
        const entry = ipPool[pIdx % ipPool.length];
        pIdx++;
        await queueEmail(email, entry.ip, campaignId, {
          ...emailOpts,
          from_name: entry.from_name || from_name,
          from_email: entry.from_email || from_email,
        });
      }

      await Campaign.findByIdAndUpdate(campaignId, {
        total_queued: firstBatch.length,
      });

      const CampaignAutoRunner = require("../services/CampaignAutoRunner");
      CampaignAutoRunner.start({
        campaignId,
        emailsList: targetEmails.slice(startIndex + firstBatch.length),
        ipPool,
        emailOpts: { ...emailOpts, dashboardLogId },
        batchSize,
        sleepSeconds: Number(sleep_time) || 5,
        inboxPercentThreshold: Number(inbox_percent) || 50,
        startIndex: startIndex + firstBatch.length, // Pass offset for IP selection continuity
      });

      const bulkAutoStartLog = await CampaignLog.create({
        campaign_id: campaignId,
        log_text: `[BULK+AUTO] Resuming/Starting from ${startIndex}. First batch of ${firstBatch.length} queued.`,
        type: "info",
      });
      socketService.emitLog(campaignId, bulkAutoStartLog, campaign);

      return res.json({
        message: `Bulk+Auto started from ${startIndex}.`,
        campaign_id: campaignId,
        count: firstBatch.length,
        total: targetEmails.length,
        mode: campaignType,
      });
    }

    // Fallback (should not reach here)
    return res.status(400).json({ message: "Unknown mode combination" });
  } catch (error) {
    console.error("Error in sendEmail:", error);
    res
      .status(500)
      .json({ message: "Error sending emails", error: error.message });
  }
};

const getDefaultIps = async (req, res) => {
  try {
    const ipRows = await IP.find({ status: "active" });
    const legacyIps = ipRows.map((r) => r.ip);

    const smtpRows = await SmtpDetail.find({});
    const accountIps = smtpRows.map((r) => {
      if (r.user && r.assignedip) {
        return `${r.assignedip}|${r.user}`;
      }
      return r.assignedip;
    });

    const combined = [...legacyIps, ...accountIps].join("\n");
    res.json({ ips: combined });
  } catch (error) {
    console.error("Error fetching default IPs from MongoDB", error);
    res.status(500).json({
      message: "Error fetching default IPs",
      error: error.message || "Unknown error",
    });
  }
};

const getCampaigns = async (req, res) => {
  try {
    const templates = await CampaignTemplate.find({}).sort({ createdAt: -1 });
    const campaigns = await Campaign.find({}).sort({ createdAt: -1 });

    const combined = [
      ...templates.map((t) => ({
        id: t._id,
        name: `${t.name}`,
        isTemplate: true,
      })),
      ...campaigns.map((c) => ({
        id: c._id,
        name: `${c.template_name}`,
        isTemplate: false,
      })),
    ];

    res.json(combined);
  } catch (error) {
    console.error("Error fetching campaigns from MongoDB", error);
    res.status(500).json({
      message: "Error fetching campaigns",
      error: error.message || "Unknown error",
    });
  }
};

const getCampaignDetails = async (req, res) => {
  try {
    let c = await CampaignTemplate.findById(req.params.id);
    if (!c) {
      c = await Campaign.findById(req.params.id);
    }

    if (!c) {
      return res.status(404).json({ message: "Campaign not found" });
    }

    const mappedData = {
      accs: c.accs || "",
      headers: c.headers || "",
      from_email: c.from_email || "",
      subject: c.subject || "",
      from_name: c.from_name || "",
      emails: c.emails || "",
      msg_type: c.msg_type || "html",
      message_html: c.message_html || "",
      message_plain: c.message_plain || "",
      search_replace: c.search_replace || "",
      data_file: c.data_file || "",
      total_send: String(c.total_send || ""),
      limit_to_send: String(c.limit_to_send || ""),
      sleep_time: String(c.sleep_time || ""),
      offer_id: c.offer_id || "",
      template_name: c.name || c.template_name || "",
      domain: c.domain || "",
      wait_time: String(c.wait_time || "2"),
      message_id: c.message_id || "",
      inbox_percent: String(c.inbox_percent || ""),
      mail_after: String(c.mail_after || ""),
      reply_to: c.reply_to || "0",
      xmailer: c.xmailer || "0",
      interval_time: String(c.interval_time || ""),
      charset: c.charset || "UTF-8",
      encoding: c.encoding || "8bit",
      charset_alt: c.charset_alt || "UTF-8",
      encoding_alt: c.encoding_alt || "8bit",
      mode: c.mode || "test",
      sen_t: c.sen_t || "manual",
      status: c.status || "0",
    };

    res.json(mappedData);
  } catch (error) {
    console.error("Error fetching campaign details from MongoDB", error);
    res.status(500).json({
      message: "Error fetching campaign details",
      error: error.message,
    });
  }
};

const getCampaignLogs = async (req, res) => {
  try {
    const logs = await CampaignLog.find({ campaign_id: req.params.campaignId })
      .sort({ updatedAt: -1 })
      .limit(100);
    res.json(logs);
  } catch (error) {
    console.error("Error fetching campaign logs", error);
    res
      .status(500)
      .json({ message: "Error fetching logs", error: error.message });
  }
};

const clearCampaignLogs = async (req, res) => {
  try {
    const { campaignId } = req.params;
    await CampaignLog.deleteMany({ campaign_id: campaignId });

    // Crucial: Reset the campaign aggregates back to zero, otherwise the new logs
    // will show inherited inflated percentages from previous test runs.
    await Campaign.findByIdAndUpdate(campaignId, {
      $set: {
        success_count: 0,
        error_count: 0,
        inbox_count: 0,
        spam_count: 0,
        promo_count: 0,
        open_count: 0,
      },
    });

    res.json({ message: "Logs and campaign stats cleared successfully" });
  } catch (error) {
    console.error("Error clearing campaign logs", error);
    res
      .status(500)
      .json({ message: "Error clearing logs", error: error.message });
  }
};

const getInboxPatterns = async (req, res) => {
  try {
    const patterns = Array.from({ length: 24 }, (_, i) => ({
      id: i + 1,
      name: `pattern ${i + 1}`,
    }));
    res.json(patterns);
  } catch (error) {
    res.status(500).json({ message: "Error fetching patterns" });
  }
};

const validateOffer = async (req, res) => {
  try {
    const offer = await Offer.findOne({ offer_id: req.params.offerId });
    if (offer) {
      res.json({ valid: true, offer_id: offer.offer_id });
    } else {
      res.json({ valid: false });
    }
  } catch (error) {
    res.status(500).json({ message: "Error validating offer" });
  }
};

/**
 * GET /api/sendEmail/campaign-status/:id
 * Returns live campaign stats for polling
 */
const getCampaignStatus = async (req, res) => {
  try {
    const campaign = await Campaign.findById(req.params.id).select(
      "status type mode sen_t success_count error_count total_emails inbox_count spam_count promo_count bounce_count total_queued guardian_logs",
    );
    if (!campaign) return res.status(404).json({ message: "Not found" });

    // Debug logging for field verification
    console.log(`[API] Campaign Status ${req.params.id}:`, {
      sent: campaign.success_count,
      inbox: campaign.inbox_count,
      spam: campaign.spam_count,
      promo: campaign.promo_count,
    });

    res.json(campaign);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * POST /api/email/start-space-sending
 * Starts the drip feed campaign
 */
const startSpaceSending = async (req, res) => {
  const {
    from_email,
    from_name,
    mailing_ip,
    headers,
    subject,
    message_html,
    message_plain,
    emails,
    subject_enc,
    from_enc,
    msg_type,
    charset,
    encoding,
    charset_alt,
    encoding_alt,
    offer_id,
    template_name,
    domain,
    message_id,
    reply_to,
    xmailer,
    total_send,
    data_file,
    search_replace,
    interval_time,
    wait_time,
    inbox_percent,
    mail_after,
    limit_to_send,
    sleep_time,
  } = req.body;

  if (!from_email || !mailing_ip || !interval_time) {
    return res.status(400).json({
      message: "Missing required fields: from_email, mailing_ip, interval_time",
    });
  }

  if (!emails && !data_file) {
    return res.status(400).json({
      message: "Either paste emails or provide a Data File name.",
    });
  }

  try {
    const ipPool = parseIpPool(mailing_ip);
    if (ipPool.length === 0) {
      return res.status(400).json({ message: "No valid IPs found." });
    }

    let rawEmailList = "";
    if (data_file && data_file.trim()) {
      const { DATA_PATH, BUFFER_PATH } = require("../config/paths");
      const fs = require("fs");
      const nodePath = require("path");

      const df = data_file.trim();
      const primaryPath = nodePath.isAbsolute(df)
        ? df
        : nodePath.join(DATA_PATH, df);
      const bufferFallbackPath = nodePath.join(
        BUFFER_PATH,
        nodePath.basename(df),
      );

      let finalPath = null;
      if (fs.existsSync(primaryPath)) finalPath = primaryPath;
      else if (fs.existsSync(bufferFallbackPath))
        finalPath = bufferFallbackPath;

      if (finalPath) {
        try {
          rawEmailList = fs.readFileSync(finalPath, "utf-8");
        } catch (fileErr) {
          rawEmailList = emails || "";
        }
      } else {
        rawEmailList = emails || "";
      }
    } else {
      rawEmailList = emails || "";
    }

    let targetEmails = rawEmailList
      .split("\n")
      .map((e) => e.trim())
      .filter(Boolean);
    if (targetEmails.length === 0) {
      return res
        .status(400)
        .json({ message: "No valid email addresses found." });
    }

    // Determine how many to send
    const limit = parseInt(total_send, 10);
    if (limit && limit > 0 && limit < targetEmails.length) {
      targetEmails = targetEmails.slice(0, limit);
    }

    const campaign = new Campaign({
      type: "space_sending",
      mode: "space",
      offer_id,
      template_name: template_name || "Space_Sending",
      domain,
      from_email,
      from_name,
      headers,
      subject,
      message_html,
      message_plain,
      emails: targetEmails.join("\n"),
      status: "Running",
      total_emails: targetEmails.length,
      success_count: 0,
      error_count: 0,
      inbox_count: 0,
      spam_count: 0,
      promo_count: 0,
      bounce_count: 0,

      // Save configuration snapshot
      accs: mailing_ip,
      subject_enc: subject_enc || "reset",
      from_enc: from_enc || "reset",
      msg_type: msg_type || "html",
      charset: charset || "UTF-8",
      encoding: encoding || "8bit",
      charset_alt: charset_alt || "UTF-8",
      encoding_alt: encoding_alt || "8bit",
      message_id,
      reply_to: reply_to || "0",
      xmailer: xmailer || "0",
      interval_time,
      search_replace,
      total_send,
      data_file,
      wait_time: wait_time || "2",
      inbox_percent: Number(inbox_percent) || 50,
      mail_after: Number(mail_after) || 100,
      limit_to_send: Number(limit_to_send) || 500,
      sleep_time: Number(sleep_time) || 5,
    });

    await campaign.save();

    // Create the initial CampaignLog
    await CampaignLog.create({
      campaign_id: campaign._id,
      type: "info",
      log_text: `Space Sending campaign started. Total targets: ${targetEmails.length}, Interval: ${interval_time}s`,
    });

    // Queue ONLY the first email to start the loop
    const firstEmail = targetEmails[0];
    const jobData = {
      email: firstEmail,
      mailing_ip: ipPool[0].ip, // emailWorker expects just 'mailing_ip' string
      campaign_id: campaign._id.toString(),
      from_email,
      from_name,
      headers,
      subject,
      body_html: message_html,
      body_plain: message_plain,
      subject_enc,
      from_enc,
      msg_type,
      charset,
      encoding,
      charset_alt,
      encoding_alt,
      offer_id,
      template_name,
      domain,
      reply_to,
      xmailer,
      search_replace,
      wait_time,
      spaceOpts: {
        // Unique props for the drip loop
        interval_time: parseInt(interval_time, 10),
        targetEmails,
        currentIndex: 0,
        ipPool,
      },
    };

    if (message_id) jobData.msgId = message_id;

    await spaceEmailQueue.add(`space-email-${campaign._id}-0`, jobData, {
      removeOnComplete: true,
      removeOnFail: 100, // Keep some failed jobs for debugging
    });

    res.status(200).json({
      message: `Space Sending started successfully. Configured for ${targetEmails.length} emails.`,
      campaignId: campaign._id,
    });
  } catch (error) {
    console.error("[startSpaceSending] Error:", error);
    res.status(500).json({ message: "Internal Server Error" });
  }
};

/**
 * POST /api/email/stop-space-sending
 * Stops the drip feed campaign
 */
const stopSpaceSending = async (req, res) => {
  try {
    const { campaignId } = req.body;
    if (!campaignId) {
      return res.status(400).json({ message: "Campaign ID required." });
    }

    const campaign = await Campaign.findById(campaignId);
    if (!campaign) {
      return res.status(404).json({ message: "Campaign not found." });
    }

    campaign.status = "Stopped";
    await campaign.save();

    await CampaignLog.create({
      campaign_id: campaign._id,
      type: "info",
      log_text: "Space Sending campaign manually stopped.",
    });

    res.status(200).json({ message: "Space Sending campaign stopped." });
  } catch (error) {
    console.error("[stopSpaceSending] Error:", error);
    res.status(500).json({ message: "Internal Server Error" });
  }
};

module.exports = {
  sendEmail,
  getCampaigns,
  getCampaignDetails,
  getDefaultIps,
  getCampaignLogs,
  clearCampaignLogs,
  getInboxPatterns,
  validateOffer,
  getCampaignStatus,
  startSpaceSending,
  stopSpaceSending,
};
